import { Box } from "@mui/material";
import { HistoryImagesGallery, HistoryImagesItems } from "./styled";

const HistoryGallery = () => {
  return (
    <Box>
      <HistoryImagesGallery>
        <HistoryImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/HistoryImages/1history.png"
          />
        </HistoryImagesItems>
        <HistoryImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/HistoryImages/2history.png"
          />
        </HistoryImagesItems>
        <HistoryImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/HistoryImages/3history.png"
          />
        </HistoryImagesItems>
        <HistoryImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/HistoryImages/4history.png"
          />
        </HistoryImagesItems>
        <HistoryImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/HistoryImages/5history.png"
          />
        </HistoryImagesItems>
        <HistoryImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/HistoryImages/6history.png"
          />
        </HistoryImagesItems>
        <HistoryImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/HistoryImages/7history.png"
          />
        </HistoryImagesItems>
        <HistoryImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/HistoryImages/8history.png"
          />
        </HistoryImagesItems>
        <HistoryImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/HistoryImages/9history.png"
          />
        </HistoryImagesItems>
        <HistoryImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/HistoryImages/10history.png"
          />
        </HistoryImagesItems>
        <HistoryImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/HistoryImages/11history.png"
          />
        </HistoryImagesItems>
        <HistoryImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/HistoryImages/12history.png"
          />
        </HistoryImagesItems>
      </HistoryImagesGallery>
    </Box>
  );
};

export default HistoryGallery;
