import { Box } from "@mui/material";
import { ModernImagesGallery, ModernImagesItems } from "./styled";
const ModernGallery = () => {
  return (
    <Box>
      <ModernImagesGallery>
        <ModernImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/ModernImages/1modern.png"
          />
        </ModernImagesItems>
        <ModernImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/ModernImages/2modern.png"
          />
        </ModernImagesItems>
        <ModernImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/ModernImages/3modern.png"
          />
        </ModernImagesItems>
        <ModernImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/ModernImages/4modern.png"
          />
        </ModernImagesItems>
        <ModernImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/ModernImages/5modern.png"
          />
        </ModernImagesItems>
        <ModernImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/ModernImages/6modern.png"
          />
        </ModernImagesItems>
        <ModernImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/ModernImages/7modern.png"
          />
        </ModernImagesItems>
        <ModernImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/ModernImages/8modern.png"
          />
        </ModernImagesItems>
        <ModernImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/ModernImages/9modern.png"
          />
        </ModernImagesItems>
        <ModernImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/ModernImages/10modern.png"
          />
        </ModernImagesItems>
        <ModernImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/ModernImages/11modern.png"
          />
        </ModernImagesItems>
        <ModernImagesItems>
          <img
            width="190px"
            height="245px"
            src="/images/ModernImages/12modern.png"
          />
        </ModernImagesItems>
      </ModernImagesGallery>
    </Box>
  );
};

export default ModernGallery;
